import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { merri } from "@/config/fonts";
import { Nav } from "@/components/MainHead/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={merri.className}>
        <Providers>
          <Nav />
          {children}
        </Providers>
      </body>
    </html>
  );
}
